### PR TITLE
Add PHP 7.2 support

### PR DESCRIPTION
**Pull request by immanuelfodor**
Renamed all occurrences of Object to OmlexObject, also includes some minor fixes from another fork.

### CODE REVIEW

**Comment by excelwebzone** [comment]
This change is unnecessary; no need to rename the `Object` folder.

**Comment by immanuelfodor** [comment]
Well, okay, I can revert that but what about the `Object` class which gives a pretty big error :astonished: 

`CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Cannot use 'Object' as class name as it is reserved" at XXX/vendor/excelwebzone/omlex/lib/Omlex/Object.php line 22`

My main goal was to eliminate this one, I just renamed everything that was Object-related.

**Comment by excelwebzone** [comment]
I will try to fix it later today

**Comment by immanuelfodor** [comment]
Okay, thank you very much!

**Pull request closed without merging**
